# Generated by Django 4.2 on 2023-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='books_images/'),
        ),
    ]
