# Generated by Django 4.2.1 on 2023-05-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0003_knjiga_brojocena_knjiga_ocena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahtevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200)),
                ('idKorisnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Zahtevi',
            },
        ),
    ]
