# Generated by Django 4.2.1 on 2023-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0005_rename_idkorisnika_zahtevi_korisnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtevi',
            name='imeKnjige',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='zahtevi',
            name='izmeniOpis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zahtevi',
            name='objaviKnjigu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zahtevi',
            name='ukloniKnjigu',
            field=models.BooleanField(default=False),
        ),
    ]
