# Generated by Django 4.2.1 on 2023-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0006_zahtevi_imeknjige_zahtevi_izmeniopis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtevi',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='zahtevi',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='books_images/'),
        ),
    ]
