# Generated by Django 4.2.1 on 2023-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0007_zahtevi_pdf_file_zahtevi_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtevi',
            name='imeNoveKnjige',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
