# Generated by Django 4.2.1 on 2023-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0008_zahtevi_imenoveknjige'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahtevi',
            name='opisNoveKnjige',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
